version: '3.8'

services:
  wifi-tracker:
    build:
      context: .
      dockerfile: Dockerfile.raspberry-pi
    container_name: wifi-tracker-pi
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
      - CORS_ORIGIN=http://localhost:3001
      - REQUEST_TIMEOUT=60000
      - SCAN_TIMEOUT=30000
      - WIFI_SCAN_INTERVAL=60000
      - DEVICE_SCAN_INTERVAL=120000
      - LOG_LEVEL=warn
      - NODE_OPTIONS=--max-old-space-size=512
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host
    privileged: true
    user: "1001:1001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/networks"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wifi-tracker.rule=Host(`wifi-tracker.local`)"
      - "traefik.http.services.wifi-tracker.loadbalancer.server.port=5001"

  # Service de monitoring (optionnel)
  monitoring:
    image: arm32v7/alpine:latest
    container_name: wifi-tracker-monitoring
    command: >
      sh -c "
        apk add --no-cache curl jq &&
        while true; do
          echo '=== WiFi Tracker Status ===' &&
          curl -s http://localhost:5001/api/networks | jq '.networks | length' &&
          echo 'Devices found:' &&
          curl -s http://localhost:5001/api/devices | jq '.devices | length' &&
          echo 'Memory usage:' &&
          free -h &&
          echo 'Temperature:' &&
          vcgencmd measure_temp 2>/dev/null || echo 'N/A' &&
          echo '=======================' &&
          sleep 60
        done
      "
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    restart: unless-stopped
    depends_on:
      - wifi-tracker
    profiles:
      - monitoring

volumes:
  logs:
    driver: local
  data:
    driver: local

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 