version: '3.8'

services:
  bonjour-network:
    build:
      context: .
      dockerfile: Dockerfile.raspberry-pi
    container_name: bonjour-network-pi
    ports:
      - "3000:3000"  # Frontend
      - "5001:5001"  # Backend
    environment:
      - NODE_ENV=production
      - PORT=5001
      - CLIENT_PORT=3000
      - LOG_LEVEL=info
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    # Accès aux interfaces réseau pour le scan WiFi
    network_mode: host
    # Privilèges nécessaires pour le scan réseau
    privileged: true
    # Sécurité : utilisation d'un utilisateur non-root
    user: "1001:1001"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5001/api/networks"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Service optionnel pour le développement
  bonjour-network-dev:
    build:
      context: .
      dockerfile: Dockerfile.raspberry-pi
    container_name: bonjour-network-pi-dev
    ports:
      - "3001:3000"  # Frontend dev
      - "5002:5001"  # Backend dev
    environment:
      - NODE_ENV=development
      - PORT=5001
      - CLIENT_PORT=3000
      - LOG_LEVEL=debug
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      # Montage du code source pour le développement
      - ./server:/app/server
      - ./client:/app/client
    restart: unless-stopped
    network_mode: host
    privileged: true
    user: "1001:1001"
    profiles:
      - dev

volumes:
  logs:
    driver: local
  data:
    driver: local

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 