version: '3.8'

services:
  bonjour-network:
    build: .
    container_name: bonjour-network
    ports:
      - "3000:3000"  # Frontend
      - "5001:5001"  # Backend
    environment:
      - NODE_ENV=production
      - PORT=5001
      - CLIENT_PORT=3000
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - bonjour-network

  bonjour-network-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: bonjour-network-dev
    ports:
      - "3001:3000"  # Frontend dev
      - "5002:5001"  # Backend dev
    environment:
      - NODE_ENV=development
      - PORT=5001
      - CLIENT_PORT=3000
      - LOG_LEVEL=debug
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./server:/app/server
      - ./client:/app/client
    restart: unless-stopped
    networks:
      - bonjour-network

networks:
  bonjour-network:
    driver: bridge 