name: Docker Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Test Docker build (main)
      run: |
        docker build -t bonjour-network-test .
        docker run --rm -d --name test-container -p 5001:5001 bonjour-network-test
        sleep 15
        curl -f http://localhost:5001/api/health || exit 1
        docker stop test-container
    
    - name: Test Docker build (Raspberry Pi)
      run: |
        docker build -f Dockerfile.raspberry-pi -t bonjour-network-raspberry-test .
        docker run --rm -d --name test-raspberry-container -p 5002:5001 bonjour-network-raspberry-test
        sleep 15
        curl -f http://localhost:5002/api/health || exit 1
        docker stop test-raspberry-container
    
    - name: Test Docker Compose
      run: |
        docker-compose up -d
        sleep 20
        curl -f http://localhost:5001/api/health || exit 1
        curl -f http://localhost:3000 || exit 1
        docker-compose down
    
    - name: Test Docker Compose Raspberry Pi
      run: |
        docker-compose -f docker-compose.raspberry-pi.yml up -d
        sleep 20
        curl -f http://localhost:5001/api/health || exit 1
        docker-compose -f docker-compose.raspberry-pi.yml down
    
    - name: Test Docker entrypoint script
      run: |
        # Vérifier que le script d'entrée existe et est exécutable
        if [ ! -f docker-entrypoint.sh ]; then
          echo "❌ docker-entrypoint.sh manquant"
          exit 1
        fi
        
        if [ ! -x docker-entrypoint.sh ]; then
          echo "❌ docker-entrypoint.sh non exécutable"
          exit 1
        fi
        
        echo "✅ docker-entrypoint.sh OK"
    
    - name: Test Docker ignore
      run: |
        # Vérifier que docker-entrypoint.sh n'est pas ignoré
        if grep -q "docker-entrypoint.sh" .dockerignore; then
          echo "❌ docker-entrypoint.sh est ignoré par .dockerignore"
          exit 1
        fi
        
        echo "✅ docker-entrypoint.sh non ignoré"
    
    - name: Cleanup
      if: always()
      run: |
        docker stop test-container test-raspberry-container 2>/dev/null || true
        docker-compose down 2>/dev/null || true
        docker-compose -f docker-compose.raspberry-pi.yml down 2>/dev/null || true 