name: Security Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1' # Tous les lundis à 2h du matin

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci
        cd client && npm ci
        cd ../server && npm ci
    
    - name: Run security audit
      run: |
        npm audit --audit-level=moderate
        cd client && npm audit --audit-level=moderate
        cd ../server && npm audit --audit-level=moderate
    
    - name: Run security tests
      run: |
        cd server
        node security/security-test.js
    
    - name: Check for secrets in code
      run: |
        # Vérifier qu'il n'y a pas de secrets dans le code
        if grep -r "password\|secret\|key\|token" . --exclude-dir=node_modules --exclude-dir=.git --exclude=*.md | grep -v "example\|test\|TODO"; then
          echo "⚠️ Possible secrets found in code"
          exit 1
        fi
    
    - name: Check file permissions
      run: |
        # Vérifier les permissions des fichiers sensibles
        find . -name "*.sh" -exec ls -la {} \;
        find . -name "*.js" -exec ls -la {} \; 